version: "3.9"
services:
  mysql:
    image: mysql:8.0.36
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "elearning"
